import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // ★←これがないとデザインが全部死にます

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Special Support Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}